name: rust

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: x86_64-apple-darwin

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - run: otool -L target/debug/test-macos-usb | grep libusb

      - uses: actions/upload-artifact@v3
        with:
          path: target/debug/test-macos-usb
